//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeatherDBEntities : DbContext
    {
        public WeatherDBEntities()
            : base("name=WeatherDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<DbUser> DbUser { get; set; }
        public virtual DbSet<DbUserType> DbUserType { get; set; }
        public virtual DbSet<WeatherHistory> WeatherHistory { get; set; }
        public virtual DbSet<vWeatherHistory> vWeatherHistory { get; set; }
        public virtual DbSet<vUsers> vUsers { get; set; }
    }
}
